const ActionTypes={
    ADD_CARD_INFO:"ADD_CARD_INFO",
    ADD_NEW_ARRIVAL:"ADD_NEW_ARRIVAL",
    ADD_MEN_CARD:"ADD_MEN_CARD",
    ADD_WOMEN_CARD:"ADD_WOMEN_CARD",
    ADD_MEN_TESTER_CARD:"ADD_MEN_TESTER_CARD",
    ADD_WOMEN_TESTER_CARD:"ADD_WOMEN_TESTER_CARD",
    RESET_CARD_REDUCER:"RESET_CARD_REDUCER",
    ADD_TO_CART:"ADD_TO_CART",
    SET_CART:"SET_CART"

}


export default ActionTypes