const ActionTypes={
    ADD_CARD_INFO:"ADD_CARD_INFO",
    ADD_NEW_ARRIVAL:"ADD_NEW_ARRIVAL",
    ADD_MEN_CARD:"ADD_MEN_CARD",
    ADD_WOMEN_CARD:"ADD_WOMEN_CARD",
    ADD_MEN_TESTER_CARD:"ADD_MEN_TESTER_CARD",
    ADD_WOMEN_TESTER_CARD:"ADD_WOMEN_TESTER_CARD",
    RESET_CARD_REDUCER:"RESET_CARD_REDUCER",
    ADD_TO_CART:"ADD_TO_CART",
    SET_CART:"SET_CART",
    SET_TOKEN:"SET_TOKEN",
    SET_IS_LOGGED_IN:"SET_IS_LOGGED_IN",
    SET_USER_INFO:"SET_USER_INFO",
    RESET_PAGE_REDUCER:"RESET_PAGE_REDUCER",
    SET_LUX_BRANDS:"SET_LUX_BRANDS",
    SET_DESIGNER_BRANDS:"SET_DESIGNER_BRANDS"


}


export default ActionTypes